const router = require("express").Router();
const auth = require("./auth");
const user = require("./user/userRoute");
const doctor = require("./doctor/doctorsRoutes");
const patient = require("./patient/patientRoute");
const clinic = require("./clinics/clinicRoutes");
const appointment = require("./apointment/apointmentRoutes");   
const meeting = require("./apointment/meetingsRoute");   
const image = require("./others/fetchImageRoute");   
const questionnaireType = require("./questionnaire/questionnaireTypeRoutes");   
const questionFolder = require("./questionnaire/questionFolderRoutes");   
const questionGroup = require("./questionnaire/questionGroupRoutes");   
const question = require("./questionnaire/questionRoutes");   
const answer = require("./questionnaire/answerRoutes");   
const platformRoute = require("./platfrom/platformRoute");   
const reports = require("./report/mainRoute");   
const upload = require("./upload/questionnaire");
router.use("/auth", auth);
router.use("/user", user);
router.use("/clinic", clinic);
router.use("/doctor", doctor);
router.use("/patient", patient);
router.use("/appointment", appointment);
router.use("/meeting", meeting);
router.use("/image", image);
router.use("/question-type", questionnaireType);
router.use("/question-folder", questionFolder);
router.use("/question-group", questionGroup);
router.use("/question", question);
router.use("/answer", answer);
router.use("/platform", platformRoute);
router.use("/reports", reports);
router.use("/upload", upload);


module.exports = router;
